package com.study.concurency.java8above.thread.interrupt;

public class PrimeGenerator extends Thread {
	
	@Override
	public void run() {
		long num = 1l;
		
		while (true) {
			if (isPrime(num)) {
				System.out.printf(" PrimeGenerator : Prime number %d generated by thread %s \n",num,this.currentThread().getName());
			}
			num++;
			
			if (isInterrupted()) {
				System.out.printf(" PrimeGenerator : Prime generator has been interrupted \n ");
				return;
			}
		}
	}

	private boolean isPrime(long primeNum) {
		boolean isPrimeNum = false;
		if (primeNum <= 2) {
			isPrimeNum = true;
			return isPrimeNum;
		}
		
		for (int i = 1; i < primeNum; i++) {
			if (primeNum%i==0) {
				isPrimeNum = true;
				break;
			}
		}
		
		return isPrimeNum;
	}
}
